compute_environment: LOCAL_MACHINE
deepspeed_config: {}
distributed_type: MULTI_GPU
downcast_bf16: 'no'
fsdp_config: {}
machine_rank: 0
main_process_ip: 192.168.25.74
main_process_port: 8000
main_training_function: main
mixed_precision: 'no'
num_machines: 2
num_processes: 3
use_cpu: false
